[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = {sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/8ZJVlrPY00Y6dTa_o_PPCj214ql6L1ty", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/8ZJVlrPY00Y6dTa_o_PPCj214ql6L1ty"}

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink-local/=lib/chainlink-local/"

]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
